app/members/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, validators
from wtforms.validators import DataRequired, Length, EqualTo, Email

class AddBookForm(FlaskForm):
    book_name = StringField('Book Name', validators=[DataRequired()])
    reason = StringField('Recipe Description', validators=[DataRequired()])


class Book_name_changeForm(FlaskForm):
    book_name = StringField('Book Name', validators=[DataRequired()])


class EditBookForm(FlaskForm):
    book_name = StringField('Book Name', validators=[DataRequired()])
    reason = StringField('Reason ', validators=[DataRequired()])

app/members/views.py
from flask import Flask, render_template, session, request, redirect, url_for, Blueprint, flash
from app.models import Book, User
from .forms import *
from app import db
from flask_login import login_user, current_user, login_required, logout_user

members_blueprint = Blueprint('members', __name__, template_folder='templates')

@members_blueprint.route('/dashboard')
@login_required
def dashboard():
    if 'email' in session:
        all_user_book = Book.query.filter_by(user_id=current_user.id)
        return render_template('dashboard.html', book=all_user_book)
    else:
        return redirect(url_for('home.index'))

@members_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add_book():
    form = AddBookForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_book = Book(form.book_name.data, form.reason.data, current_user.id, False)
            db.session.add(new_book)
            db.session.commit()
            return redirect(url_for('members.dashboard'))
    return render_template('add_book.html', form=form)


@members_blueprint.route('/book_delete/<book_id>')
def book_delete(book_id):
    data = db.session.query(Book, User).join(User).filter(Book.id == book_id).first()
    if data.Book.is_public:
        return render_template('book_detail.html', book=data)
    else:
        if current_user.is_authenticated and data.Book.user_id == current_user.id:
            data = Book.query.filter_by(id=book_id).first()
            db.session.delete(data)
            db.session.commit()
    return redirect(url_for('members.dashboard'))


@members_blueprint.route('/book_edit/<book_id>', methods=['GET', 'POST'])
def book_edit(book_id):
    data = db.session.query(Book, User).join(User).filter(Book.id == book_id).first()
    form = EditBookForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            if current_user.is_authenticated and data.Book.user_id == current_user.id:
                data = Book.query.filter_by(id=book_id).first()
                new_book_name = form.book_name.data
                new_reason = form.reason.data
                try:
                    data.book_name = new_book_name
                    data.reason= new_reason
                    db.session.commit()

                except Exception as e:
                    return {'error': str(e)}
            return redirect(url_for('members.dashboard'))

    return render_template('edit_book.html', form=form, book=data)


@members_blueprint.route('/book/<book_id>')
def book_details(book_id):
    book_with_user = db.session.query(Book, User).join(User).filter(Book.id == book_id).first()
    if book_with_user is not None:
        if book_with_user.Book.is_public:
            return render_template('book_detail.html', book=book_with_user)
        else:
            if current_user.is_authenticated and book_with_user.Book.user_id == current_user.id:
                return render_template('book_detail.html', book=book_with_user)
    else:
        flash('Error! Recipe does not exist.', 'error')
    return redirect(url_for('home.index'))

app/members/templates/add_book.html
{% extends "theme.html" %}

{% block title %}
	{{ super() }}
    Add Book
{% endblock %}

{% block body %}
    {{ super() }}
    <div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Add Book Page</h2>
    </div>
	</div>
	<div class="row">
	    <div class="col-lg-12">
	        <div class="panel panel-info">
	            <div class="panel-heading">

	            </div>
	            <!-- /.panel-heading -->
	            <div class="panel-body">

                    <div class="page-header">
                        <h2>Add Book</h2>
                    </div>

                    <form action="{{url_for('members.add_book')}}" method="post">
                        {{ form.csrf_token }}
                        {{ form.book_name(placeholder="Book Name") }}
                        {{ form.reason(placeholder="Reason ") }}
                        <button class="btn btn-sm btn-success" type="submit">Add Book</button>
                    </form>

                </div>
	            <!-- /.panel-body -->
	        </div>
	        <!-- /.panel -->
	    </div>
	    <!-- /.col-lg-12-->
	</div>
{% endblock %}

app/members/templates/book_detail.html
{% extends "theme.html" %}
{% block body %}

<div class="user-profile">
  <div class="page-header">
    <h2>ID : {{ book.Book.id }}</h2>
  </div>

  <div class="row">
      <div class="panel panel-primary">
        <div class="panel-heading">Book Name</div>
        <div class="panel-body">{{ book.Book.book_name }}</div>

      </div>

    <div class="panel panel-primary">
      <div class="panel-heading">Reason</div>
      <div class="panel-body">{{ book.Book.reason }}</div>
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">Public or Private</div>
      {% if book.Book.is_public %}
        <div class="panel-body">Public</div>
      {% else %}
        <div class="panel-body">Private</div>
      {% endif %}
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">User</div>
      <div class="panel-body">{{ book.User.email }}</div>
    </div>

  </div>
</div>`

{% endblock %}

app/members/templates/dashboard.html
{% extends "theme.html" %}

{% block title %}
    Dashboard
{% endblock %}

{% block body %}

    <div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Dashboard Page</h2>
    </div>
	</div>
	<div class="row">
	    <div class="col-lg-12">
	        <div class="panel panel-info">
	            <div class="panel-heading">

	            </div>
	            <!-- /.panel-heading -->
	            <div class="panel-body">
					<div class="dataTable_wrapper">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Nama</th>
									<th>Reason </th>
                                    <th>Action</th>
								</tr>
							</thead>
							<tbody>
							{% for list in book %}
								<tr class="odd gradeX">
									<td><a href="{{ url_for('members.book_details', book_id=list.id) }}">{{ list.book_name }}</a></td>
									<td>{{ list.reason }}</td>
                                    <td>
                                        <a href="{{ url_for('members.book_delete', book_id=list.id) }}">Delete</a>
                                        |
                                        <a href="{{ url_for('members.book_edit', book_id=list.id) }}">Edit</a>
                                    </td>
								</tr>
							{% endfor %}
							</tbody>
						</table>
					</div>
	            </div>
	            <!-- /.panel-body -->
	        </div>
	        <!-- /.panel -->
	    </div>
	    <!-- /.col-lg-12-->
	</div>
{% endblock %}

app/members/templates/edit_book.html
{% extends "theme.html" %}

{% block title %}
	{{ super() }}
    Add Book
{% endblock %}

{% block body %}
    {{ super() }}
    <div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Edit Book Page</h2>
    </div>
	</div>
	<div class="row">
	    <div class="col-lg-12">
	        <div class="panel panel-info">
	            <div class="panel-heading">

	            </div>
	            <!-- /.panel-heading -->
	            <div class="panel-body">

                    <div class="page-header">
                        <h2>Edit</h2>
                    </div>

                    <form action="{{url_for('members.book_edit', book_id=book.Book.id)}}" method="post">
                        {{ form.csrf_token }}
                        {{ form.book_name(value = book.Book.book_name) }}
                        {{ form.reason(value=book.Book.reason) }}
                        <button class="btn btn-sm btn-success" type="submit">Edit Book</button>
                    </form>

                </div>
	            <!-- /.panel-body -->
	        </div>
	        <!-- /.panel -->
	    </div>
	    <!-- /.col-lg-12-->
	</div>
{% endblock %}

app/members/templates/edit_mantan.html
{% extends "theme.html" %}

{% block title %}
	{{ super() }}
    Tambah Mantan
{% endblock %}

{% block body %}
    {{ super() }}
    <div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Halaman Dashboard</h2>
    </div>
	</div>
	<div class="row">
	    <div class="col-lg-12">
	        <div class="panel panel-info">
	            <div class="panel-heading">

	            </div>
	            <!-- /.panel-heading -->
	            <div class="panel-body">

                    <div class="page-header">
                        <h2>Edit</h2>
                    </div>

                    <form action="{{url_for('members.mantan_edit', mantan_id=mantan.Mantan.id)}}" method="post">
                        {{ form.csrf_token }}
                        {{ form.nama_mantan(value = mantan.Mantan.nama_mantan) }}
                        {{ form.alasan_putus(value=mantan.Mantan.alasan_putus) }}
                        <button class="btn btn-sm btn-success" type="submit">Edit Mantan</button>
                    </form>

                </div>
	            <!-- /.panel-body -->
	        </div>
	        <!-- /.panel -->
	    </div>
	    <!-- /.col-lg-12-->
	</div>
{% endblock %}

app/members/templates/mantan_detail.html
{% extends "theme.html" %}
{% block body %}

<div class="user-profile">
  <div class="page-header">
    <h2>ID : {{ mantan.Mantan.id }}</h2>
  </div>

  <div class="row">
      <div class="panel panel-primary">
        <div class="panel-heading">Nama Mantan</div>
        <div class="panel-body">{{ mantan.Mantan.nama_mantan }}</div>

      </div>

    <div class="panel panel-primary">
      <div class="panel-heading">Alasan Putus</div>
      <div class="panel-body">{{ mantan.Mantan.alasan_putus }}</div>
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">Public or Private</div>
      {% if mantan.Mantan.is_public %}
        <div class="panel-body">Public</div>
      {% else %}
        <div class="panel-body">Private</div>
      {% endif %}
    </div>

    <div class="panel panel-primary">
      <div class="panel-heading">User</div>
      <div class="panel-body">{{ mantan.User.email }}</div>
    </div>

  </div>
</div>`

{% endblock %}

app/members/templates/tambah_mantan.html
{% extends "theme.html" %}

{% block title %}
	{{ super() }}
    Tambah Mantan
{% endblock %}

{% block body %}
    {{ super() }}
    <div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Halaman Dashboard</h2>
    </div>
	</div>
	<div class="row">
	    <div class="col-lg-12">
	        <div class="panel panel-info">
	            <div class="panel-heading">

	            </div>
	            <!-- /.panel-heading -->
	            <div class="panel-body">

                    <div class="page-header">
                        <h2>Tambahkan Mantanmu</h2>
                    </div>

                    <form action="{{url_for('members.tambah_mantan')}}" method="post">
                        {{ form.csrf_token }}
                        {{ form.nama_mantan(placeholder="Nama Mantan") }}
                        {{ form.alasan_putus(placeholder="Alasan Putus") }}
                        <button class="btn btn-sm btn-success" type="submit">Tambah Mantan</button>
                    </form>

                </div>
	            <!-- /.panel-body -->
	        </div>
	        <!-- /.panel -->
	    </div>
	    <!-- /.col-lg-12-->
	</div>
{% endblock %}