app/users/views.py
# app/users/views.py


#################
#### imports ####
#################

from flask import Flask, render_template, session, request, redirect, url_for, Blueprint, flash, abort
from .forms import *
from app import db, mail, app
from sqlalchemy.exc import IntegrityError
from app.models import User
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message
from threading import Thread
from datetime import datetime
from itsdangerous import URLSafeTimedSerializer

#import sqlite3 as sql

################
#### config ####
################

users_blueprint = Blueprint('users', __name__, template_folder='templates')

##########################
#### helper functions ####
##########################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')


def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def send_email(subject, recipients, html_body):
    msg = Message(subject, recipients=recipients)
    msg.html = html_body
    thr = Thread(target=send_async_email, args=[msg])
    thr.start()


def send_confirmation_email(user_email):
    confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    confirm_url = url_for(
        'users.confirm_email',
        token=confirm_serializer.dumps(user_email, salt='email-confirmation-salt'),
        _external=True)

    html = render_template(
        'email_confirmation.html',
        confirm_url=confirm_url)

    send_email('Confirm Your Email Address', [user_email], html)

def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])

    password_reset_url = url_for(
        'users.reset_with_token',
        token=password_reset_serializer.dumps(user_email, salt='password-reset-salt'),
        _external=True)

    html = render_template(
        'email_password_reset.html',
        password_reset_url=password_reset_url)

    send_email('Password Reset Requested', [user_email], html)




################
#### routes ####
################

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                send_confirmation_email(new_user.email)
                flash('Thanks for registering!  Please check your email to confirm your email address.', 'success')
                return redirect(url_for('users.login'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)


@users_blueprint.route('/login',  methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            session['email'] = request.form['email']
            user = User.query.filter_by(email=form.email.data).first()
            if user is not None and user.is_correct_password(form.password.data):
                user.authenticated = True
                user.last_logged_in = user.current_logged_in
                user.current_logged_in = datetime.now()
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(url_for('members.dashboard'))
            else:
                flash('ERROR! Incorrect login credentials.', 'error')

    return render_template('login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    session.pop('email', None)
    flash('Goodbye!', 'info')
    return redirect(url_for('users.login'))


@users_blueprint.route('/confirm/<token>')
def confirm_email(token):
    try:
        confirm_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = confirm_serializer.loads(token, salt='email-confirmation-salt', max_age=3600)
    except:
        flash('The confirmation link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    user = User.query.filter_by(email=email).first()

    if user.email_confirmed:
        flash('Account already confirmed. Please login.', 'info')
    else:
        user.email_confirmed = True
        user.email_confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Thank you for confirming your email address!', 'success')

    return redirect(url_for('users.login'))

@users_blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return render_template('password_reset_email.html', form=form)

        if user.email_confirmed:
            send_password_reset_email(user.email)
            flash('Please check your email for a password reset link.', 'success')
        else:
            flash('Your email address must be confirmed before attempting a password reset.', 'error')
        return redirect(url_for('users.login'))

    return render_template('password_reset_email.html', form=form)


@users_blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=3600)
    except:
        flash('The password reset link is invalid or has expired.', 'error')
        return redirect(url_for('users.login'))

    form = PasswordForm()

    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=email).first_or_404()
        except:
            flash('Invalid email address!', 'error')
            return redirect(url_for('users.login'))

        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_password_with_token.html', form=form, token=token)


@users_blueprint.route('/user_profile')
@login_required
def user_profile():
    return render_template('user_profile.html')



@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
    form = EmailForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user_check = User.query.filter_by(email=form.email.data).first()
                if user_check is None:
                    user = current_user
                    user.email = form.email.data
                    user.email_confirmed = False
                    user.email_confirmed_on = None
                    user.email_confirmation_sent_on = datetime.now()
                    db.session.add(user)
                    db.session.commit()
                    send_confirmation_email(user.email)
                    flash('Email changed!  Please confirm your new email address (link sent to new email).', 'success')
                    return redirect(url_for('users.user_profile'))
                else:
                    flash('Sorry, that email already exists!', 'error')
            except IntegrityError:
                flash('Error! That email already exists!', 'error')
    return render_template('email_change.html', form=form)



@users_blueprint.route('/username_change', methods=["GET", "POST"])
@login_required
def user_username_change():
    form = UsernameForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user_check = User.query.filter_by(username=form.username.data).first()
            if user_check is None:
                user = current_user
                user.username = form.username.data
                db.session.add(user)
                db.session.commit()
                flash('Username Changed', 'success')
                return redirect(url_for('users.user_profile'))
            else:
                flash('Sorry, that username already exists!', 'error')
                return redirect(url_for('users.user_profile'))
    return render_template('username_change.html', form=form)


@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
    form = PasswordForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = current_user
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Password has been updated!', 'success')
            return redirect(url_for('users.user_profile'))

    return render_template('password_change.html', form=form)


@users_blueprint.route('/resend_confirmation')
@login_required
def resend_email_confirmation():
    try:
        send_confirmation_email(current_user.email)
        flash('Email sent to confirm your email address.  Please check your email!', 'success')
    except IntegrityError:
        flash('Error!  Unable to send email to confirm your email address.', 'error')

    return redirect(url_for('users.user_profile'))


@users_blueprint.route('/admin_view_users')
@login_required

app/users/templates/admin_view_users.html
{% extends "theme.html" %}
{% from "_form_macros.html" import render_field %}

{% block body %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Administrative Page: List of Users</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>Role</th>
          <th>Registration Date</th>
          <th>Email Confirmed?</th>
          <th>Email Confirmed On</th>
          <th>Last Login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.role }} </td>
            <td> {{ user.registered_on }} </td>
            <td> {{ user.email_confirmed }} </td>
            <td> {{ user.email_confirmed_on }}% </td>
            <td> {{ user.last_logged_in }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

app/users/templates/email_change.html
{% extends "login_layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Change Email
{% endblock %}

{% block body %}
<div class="container">
  <section id="content">
    <div class="form">
      <form action="{{ url_for('users.user_email_change') }}" method="POST">
      {{ form.csrf_token }}
        <dl>
          {{ render_field(form.email, placeholder="Enter New Email Address") }}
        </dl>
        <button class="btn btn-sm btn-success" type="submit">Update</button>
      </form>
    </div>
  </div>
</div>


{% endblock %}

app/users/templates/email_confirmation.html
Akunmu sudah dibuat, Tolong klik link berikut untuk konfirmasi:

<a href="{{ confirm_url }}">{{ confirm_url }}</a>

--
Questions? Comments? Email akhisyabab@gmail.com.

app/users/templates/email_password_reset.html
You requested that the password for your account be reset.
Please click the link below to reset your password:

<p>
<a href="{{ password_reset_url }}">{{ password_reset_url }}</a>
</p>

<p>
--<br>
Questions? Comments? Email akhisyabab@gmail.com.
</p>

app/users/templates/login.html
{% extends "login_layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Login
{% endblock %}

{% block body %}
<div class="container">
  {% for error_message in get_flashed_messages(category_filter=["error"]) %}
    <div class="alert alert-danger alert-dismissible text-center">{{ error_message }}</div>
  {% endfor %}

  {% for success_message in get_flashed_messages(category_filter=["success"]) %}
    <div class="alert alert-success alert-dismissible text-center">{{ success_message }}</div>
  {% endfor %}

  {% for info_message in get_flashed_messages(category_filter=["info"]) %}
    <div class="alert alert-info alert-dismissible text-center">{{ info_message }}</div>
  {% endfor %}

  <section id="content">
    <form action="{{ url_for('users.login') }}" method="post">
      <h1>Login Form</h1>
      {{ form.csrf_token }}
      {{ render_field(form.email, placeholder="Email address") }}
      {{ render_field(form.password, placeholder="Password") }}
      <div>
        <input type="submit" />
        <a href="/reset">Lost your password?</a>
        <a href="/register">Register</a>
      </div>
    </form><!-- form -->
  </section><!-- content -->
</div><!-- container -->








<!--        <form action="http://localhost:5000/login" method="post">
            <a href="/">
                <div class="thumbnail"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/169963/hat.svg"/></div>
            </a>

            {{ form.csrf_token }}
            <input type="text" placeholder="Username" name="username"/>
            <input type="password" placeholder="Password" name="password"/>
            <input type="submit" value="masuk">
        </form>
-->
    </div>
{% endblock %}

app/users/templates/login_layout.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="utf-8">
  <title>Favorite Book App -- {% block title %}{% endblock %}</title>
  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700|Lato:400,100,300,700,900' rel='stylesheet' type='text/css'>

  <link href="{{ url_for('static',filename='bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom Stylesheet -->
  <link rel="stylesheet" href="{{ url_for('static',filename='login/css/style.css')}}">

</head>

<body>

{% block body %}{% endblock %}

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="{{ url_for('static',filename='login/js/login.js')}}"></script>

</body>
</html>

app/users/templates/password_change.html
{% extends "login_layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Change Password
{% endblock %}

{% block body %}

<div class="container">
  <section id="content">
    <div class="form">
      <form action="{{ url_for('users.user_password_change') }}" method="POST">
      {{ form.csrf_token }}
        <dl>
          {{ render_field(form.password, placeholder="Enter New Password") }}
        </dl>
        <button class="btn btn-sm btn-success" type="submit">Update</button>
      </form>
    </div>
  </section>

</div>



{% endblock %}

app/users/templates/password_reset_email.html
{% extends "login_layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Reset
{% endblock %}

{% block body %}
<div class="container">
  <section id="content">
    <form action="{{ url_for('users.reset') }}" method="POST">
      <h1>Reset Password</h1>
      {{ form.csrf_token }}
      {{ render_field(form.email, placeholder="Enter Email Address", id="username") }}
      <div>
        <input type="submit" />
        <a href="/login">Login</a>
      </div>
    </form><!-- form -->
  </section><!-- content -->
</div><!-- container -->

{% endblock %}

app/users/templates/register.html
{% extends "login_layout.html" %}
{% from "_form_macros.html" import render_field %}


{% block title %}
    {{ super() }}
    Register
{% endblock %}

{% block body %}
    <div class="container">
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible text-center">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible text-center">{{ success_message }}</div>
        {% endfor %}

        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible text-center">{{ info_message }}</div>
        {% endfor %}
        <section id="content">
          <form action="{{ url_for('users.register') }}" method="post">
            <h1>Register Form</h1>
            {{ form.csrf_token }}
            {{ render_field(form.email, placeholder="Email address") }}
            {{ render_field(form.password, placeholder="Password") }}
            {{ render_field(form.confirm, placeholder="Confirm password", id="password") }}
            <div>
              <input type="submit" />
              <a href="/login">Login</a>
            </div>
          </form><!-- form -->
        </section><!-- content -->
	</div>
{% endblock %}

app/users/templates/reset_password_with_token.html
{% extends "login_layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Reset
{% endblock %}

{% block body %}

<div class="container">
  <section id="content">
    <form action="{{ url_for('users.reset_with_token', token=token) }}" method="POST">
      <h1>Reset Password</h1>
      {{ form.csrf_token }}
      {{ render_field(form.password, placeholder="Enter New Password") }}
      <div>
        <input type="submit" />
      </div>
    </form><!-- form -->
  </section><!-- content -->
</div><!-- container -->



{% endblock %}

app/users/templates/result.html
<!doctype html>
<html>
   <body>

      result of addition : {{ msg }}
      <h2><a href = "\">go back to home page</a></h2>

   </body>
</html>

app/users/templates/user_profile.html
{% extends "theme.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Profile
{% endblock %}

{% block body %}

  {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible text-center">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible text-center">{{ success_message }}</div>
        {% endfor %}

        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible text-center">{{ info_message }}</div>
  {% endfor %}
  <div class="page-header">
    <h2>User Profile</h2>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">Email Address</div>
        <div class="panel-body">{{current_user.email}}</div>
        <div class="panel-body"><a href="{{ url_for('users.user_email_change') }}">Change Email</a></div>
      </div>

      <div class="panel panel-primary">
        <div class="panel-heading">Username</div>
        <div class="panel-body">{{current_user.username}}</div>
        <div class="panel-body"><a href="{{ url_for('users.user_username_change') }}">Change Username</a></div>
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">Account Actions</div>


        <div class="panel-body"><a href="{{ url_for('users.user_password_change') }}">Change Password</a></div>
        {% if not current_user.email_confirmed %}
          <div class="panel-body"><a href="{{ url_for('users.resend_email_confirmation') }}">Resend Email Confirmation</a></div>
        {% endif %}
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">Statistics</div>
        <div class="panel-body">Member since: {{ current_user.registered_on.strftime("%A %B %d, %Y") }}</div>
        {% if current_user.last_logged_in != None %}
          <div class="panel-body">Last Logged In: {{ current_user.last_logged_in.strftime("%A %B %d, %Y") }}</div>
        {% else %}
          <div class="panel-body">First time logged in. Welcome!</div>
        {% endif %}
        {% if current_user.email_confirmed %}
          <div class="panel-body">Email confirmed on: {{ current_user.email_confirmed_on.strftime("%A %B %d, %Y") }}</div>
        {% else %}
          <div class="panel-body">Email has not been confirmed!</div>
        {% endif %}
      </div>
    </div>
  </div>


{% endblock %}

app/users/templates/username_change.html
{% extends "login_layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Change Username
{% endblock %}

{% block body %}
<div class="form">
  <form action="{{ url_for('users.user_username_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.username, placeholder="Enter New Username") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>

{% endblock %}